words = [
    "bev",
    "bi≈Ñkowski",
    "bmse",
    "bottomrule",
    "cdot",
    "citeauthor",
    "controlnet",
    "convolutional",
    "cref",
    "crossviewdiff",
    "cvpr",
    "denoise",
    "dte",
    "echet",
    "ewen",
    "gdal",
    "geolocation",
    "geometryaware",
    "globalloco",
    "hline",
    "includegraphics",
    "ive",
    "jez",
    "jezero",
    "jpl",
    "maki",
    "mathieu",
    "mathrm",
    "mispredict",
    "mmd",
    "mse",
    "msl",
    "nabla",
    "navcam",
    "orthomoasics",
    "pds",
    "psnr",
    "reprojected",
    "reprojection",
    "rombach",
    "seti",
    "ssim",
    "szegedy",
    "textbf",
    "toker",
    "trn",
    "usgs",
    "verma",
    "willford",
    "zhang",
]
