words = [
    "bev",
    "bi≈Ñkowski",
    "bmse",
    "bottomrule",
    "cdot",
    "citeauthor",
    "controlnet",
    "convolutional",
    "crossviewdiff",
    "cvpr",
    "denoise",
    "dte",
    "echet",
    "geometryaware",
    "globalloco",
    "hline",
    "ive",
    "mathieu",
    "mathrm",
    "mispredict",
    "mmd",
    "mse",
    "nabla",
    "orthomoasics",
    "psnr",
    "reprojected",
    "reprojection",
    "rombach",
    "ssim",
    "szegedy",
    "toker",
    "verma",
    "zhang",
]
